### ISSUE TITLE
doesnt show up available

### ISSUE THREAD

**Issue by jhealy** [fleckert/AzureDevOpsExtensions#1]
I add to my org and it doesnt show up in the list.
It does show up as an available extension, but just not in the widget list for the dashboards.

**Comment by fleckert** [comment]
@jhealy please let me know what extension you installed in your Azure DevOps organization.

**Comment by wheel7** [comment]
Hi. I think I have the same problem. I installed the "Release Deployments" extensions, but I can't seem to find it. It doesn't show up in the installed Extensions for my organization.

**Comment by fleckert** [comment]
Hi @wheel7,
the extension will be listed at https://dev.azure.com/your-organization/_settings/extensions

![image](https://user-images.githubusercontent.com/2217206/153573026-d1a4abbc-d37c-4c71-85a0-ea4d4a987d90.png)

and can be used from

![image](https://user-images.githubusercontent.com/2217206/153573416-cc721774-493c-4ef1-9492-2d718d313ca7.png)

Please let me know if there are any other questions.

**Comment by wheel7** [comment]
Hi. Thanks for your quick reply. The problem is that it doesn't show up in my Organization Extenions. However, the Release Deployments do show up in my project, so it's working.

Would it be possible to add the branch name to that overview?

<img width="212" alt="image" src="https://user-images.githubusercontent.com/36896126/153574362-caad36b3-60dc-4f0f-9c6a-f898da3e27d6.png">

**Comment by wheel7** [comment]
Or the version number to the left of that. Or do we need to change the "Release-1998" into the actual version of the release?

**Comment by fleckert** [comment]
can you please share a screenshot of the 'current' behaviour and maybe sketch the 'desired' state... I am not a 100% sure I get the ask.

if you don't want to publicly share this, please feel free to email me at support@expectingsnow.com

**Comment by fleckert** [comment]
the build name of the primary artefact is displayed, I hope this helps

![image](https://user-images.githubusercontent.com/2217206/154048364-bed08698-6c4c-4514-afdf-fe427696d209.png)
